require_relative '../Utilities/common'

subspec_suffix = ENV['MOENGAGE_KMM_FREE'] ? '/Core' : ''
puts "Adding subspec suffix: #{subspec_suffix}"

# bridge abstract targets to include tests
abstract_target 'BridgeiOS' do
  platform :ios, '13.0'
  use_frameworks!
  pod 'mParticle-MoEngage', :testspecs => ['Tests'], :path => '../' # comment/remove :path to test released package
end

abstract_target 'BridgetvOS' do
  platform :tvos, '13.0'
  use_frameworks!
  pod 'mParticle-MoEngage', :testspecs => ['Tests'], :path => '../' # comment/remove :path to test released package
end

target 'MoEngageCocoaApp' do
  platform :ios, '13.0'
  use_frameworks!

  # Pods for MoEngageCocoaApp
  pod "mParticle-MoEngage#{subspec_suffix}", :path => '../' # comment/remove :path to test released package

  # Development source setup
  dev_source = MPKit.dev_source
  if dev_source
    pod 'MoEngageSecurity', **dev_source
    pod 'MoEngageCore', **dev_source
    pod 'MoEngageMessaging', **dev_source
    pod 'MoEngageSDK', **dev_source
    pod 'MoEngage-iOS-SDK', **dev_source
  end

  target 'NotificationContent' do
    use_frameworks!
    inherit! :search_paths

    # Pods for NotificationContent
    if dev_source
      pod 'MoEngage-iOS-SDK/RichNotification', **dev_source
      pod 'MoEngageRichNotification', **dev_source
    else
      pod 'MoEngage-iOS-SDK/RichNotification'
    end
  end

  target 'NotificationService' do
    use_frameworks!
    inherit! :search_paths

    # Pods for NotificationService
    if dev_source
      pod 'MoEngage-iOS-SDK/RichNotification', **dev_source
      pod 'MoEngageRichNotification', **dev_source
    else
      pod 'MoEngage-iOS-SDK/RichNotification'
    end
  end
end

target 'MoEngageCocoaTVApp' do
  platform :tvos, '13.0'
  use_frameworks!

  # Pods for MoEngageCocoaTVApp
  pod "mParticle-MoEngage#{subspec_suffix}", :path => '../' # comment/remove :path to test released package

  # Development source setup
  dev_source = MPKit.dev_source
  if dev_source
    pod 'MoEngageSecurity', **dev_source
    pod 'MoEngageCore', **dev_source
    pod 'MoEngageMessaging', **dev_source
    pod 'MoEngageSDK', **dev_source
    pod 'MoEngage-iOS-SDK', **dev_source
  end
end
