name: Run tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      environment_variables:
        description: Custom space separated environment variables, that can be used for setup task
        type: string
        required: false
        default: ''

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cocoapods:
    name: Build and run tests for CocoaPods
    runs-on: macos-latest

    steps:
    - name: Set custom environment variables
      if: github.event_name == 'workflow_dispatch'
      run: |
        VARIABLES=(${{ inputs.environment_variables }})
        for variable in ${VARIABLES[@]}; do
          echo "$variable" >> $GITHUB_ENV
        done

    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Checkout sdk automation scripts
      uses: actions/checkout@v4
      with:
        repository: moengage/sdk-automation-scripts
        path: sdk-automation-scripts
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Setup iOS
      uses: ./sdk-automation-scripts/actions/ios-action-setup
      env:
        SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Build and Run tests
      working-directory: Examples
      run: |
        set -eo pipefail
        rake setup
        rake test:pods

  swift-package:
    name: Build and run tests for Swift Package Manager
    runs-on: macos-latest

    steps:
    - name: Set custom environment variables
      if: github.event_name == 'workflow_dispatch'
      run: |
        VARIABLES=(${{ inputs.environment_variables }})
        for variable in ${VARIABLES[@]}; do
          echo "$variable" >> $GITHUB_ENV
        done

    - name: Checkout source repository
      uses: actions/checkout@v4

    - name: Checkout sdk automation scripts
      uses: actions/checkout@v4
      with:
        repository: moengage/sdk-automation-scripts
        path: sdk-automation-scripts
        token: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Setup iOS
      uses: ./sdk-automation-scripts/actions/ios-action-setup
      env:
        SDK_BOT_ACCESS_TOKEN: ${{ secrets.SDK_BOT_ACCESS_TOKEN }}

    - name: Build and Run tests
      run: rake test:spm
